apiVersion: v1
kind: Pod
metadata:
  name: sidecar
  labels:
    app: sync-index-from-git
spec:
  containers:
    - name: web
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx
          name: html
    - name: sync
      image: k8s.gcr.io/git-sync:v3.1.6
      volumeMounts:
        - mountPath: /tmp/git
          name: html
      env:
        - name: GIT_SYNC_REPO
          value: https://github.com/tusharthapliyal/ps-sidecar.git
        - name: GIT_SYNC_BRANCH 
          value: master
        - name: GIT_SYNC_DEPTH
          value: "1"
        - name: GIT_SYNC_DEST 
          value: "html"
  volumes:
    - name: html
      emptyDir: {}
