apiVersion: v1
kind: Service 
metadata:
  name: sync-index-from-git-svc
  labels:
    app: sync-index-from-git
spec:
  selector: 
    app: sync-index-from-git
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
