apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      targetPort: 8080 # default value is set equal to port

